# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "alembic"
]
fix = true
line-length = 100
# Allow fix for all enabled rules (when `--fix`) is provided.


[lint]
fixable = ["ALL"]
unfixable = []
select = ["ALL"]
ignore = [
    "D100",
    "E701",
    "D101",
    "D102",
    "D103",
    "D105",
    "D107",
    "D2",
    "D415",
    "BLE001",
    "PLR0912",
    "PLR0915",
    "PLR2004",
    "E501",
    "ANN001",
    "ANN002",
    "ANN003",
    "ANN201",
    "ANN202",
    "ANN204",
    "ANN401",
    "RUF",
    "SIM102",
    "SIM300",
    "E711",
    "DTZ",
    "ERA001",
    "I001",
    "C901",
    "S104",
    "FBT",
    "TRY400",
    "G004",
    "EM102",
    "TRY003",
    "B008",
    "PLR0913",
    "TRY300",
    "COM812"
]


[lint.pydocstyle]
convention = "google"

[lint.mccabe]
max-complexity = 12

[lint.pep8-naming]
classmethod-decorators = [
    "classmethod",
    "sqlalchemy.ext.declarative.declared_attr",
    "sqlalchemy.orm.declared_attr.directive",
    "sqlalchemy.orm.declared_attr",
]

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"